### PR TITLE
Update vpp-agent to v3.2.0

### PR DESCRIPTION
**Pull request by ondrej-fabry**
This PR updates vpp-agent to v3.2.0.

### CODE REVIEW

**Comment by ondrej-fabry** [comment]
@tiswanso Tim, what about docker images, e.g. vppagent-forwarder, is the vl3_latest image expected to be ovewritten or should we define some versioning here. Changes in vpp-agent should be backwards compatible so it should not hurt to use newer version when `*latest` gets updated.

**Comment by tiswanso** [comment]
> @tiswanso Tim, what about docker images, e.g. vppagent-forwarder, is the vl3_latest image expected to be ovewritten or should we define some versioning here. Changes in vpp-agent should be backwards compatible so it should not hurt to use newer version when `*latest` gets updated.

We're making vl3_latest be the current head tag and we manually apply version tags to the repo which triggers image build & tag for the images corresponding to those tags.  So, we can pin dependent imports and NSM deployments to the same tag ID to get version coupling.

**Comment by ondrej-fabry** [comment]
@tiswanso how come I still cannot set anyone for review?

Anyway, can this be merged?

**Review by tiswanso — APPROVED** [review]
sorry for delay.... I pulled this and tested it.  Seems to work :-)

**Pull request merged**
