### PR TITLE
NSMNSE-83 NSE IPAM exhaustion on repeated connection failure

### PR DESCRIPTION
**Pull request by ondrej-fabry**
Fix releasing extracted prefixes on request failures.

## Motivation and Context
This PR fixes a bug that occurred when Request kept failing to send DP config to agent until all prefixes were exhausted and IPAM endpoint's Request began returning following error:
```
IPAM: The available address pool is empty, probably intersected by excludedPrefix
```

JIRA issue: [NSMNSE-83](https://jira-eng-sjc4.cisco.com/jira/browse/NSMNSE-83)

### CODE REVIEW

**Comment by ondrej-fabry** [comment]
Still unable to add reviewers.. so, @tiswanso @CosminNechifor @panyuenlau @shanchunyang0919 please review this PR

**Review by CosminNechifor — APPROVED** [review]
LGTM

**Comment by panyuenlau** [comment]
LGTM

**Comment by tiswanso** [comment]
Hi guys, let's wait on merging this until I get the PR ready for having the CI auto populate the goproxy content.  Otherwise we'll have to do a bunch of manual steps or use go.mod replace rules so that we can use the SDK version.

**Review by tiswanso — CHANGES_REQUESTED** [review]
hold until jenkins pipeline for goproxy update in place

**Comment by ondrej-fabry** [comment]
PR migrated to internal github: https://wwwin-github.cisco.com/cisco-app-networking/networkservicemesh/pull/10

**Pull request closed without merging**
