### PR TITLE
NSM forwarder fix: add ability to set client interface MTU

### PR DESCRIPTION
**Pull request by rastislavs**
This PR adds the ability to properly set client interface MTU:
 - each local/remote connection mechanism can specify its MTU overhead
 - NSE can set its MTU overhead in the connection context (e.g. `request.Connection.Context.SetMTUOverhead(50)`)
 - the forwarder will substract the largest MTU overhead in used mechanisms and connection context from the MTU discovered on the egress interface
- the resulting MTU is applied on the client interface

### CODE REVIEW

**Comment by tiswanso** [comment]
This looks like a good start that will potentially give us the ability to make NSEs able to pass a custom MTU overhead through to any connections they're involved with.  The drawback is that it definitely requires our current NSEs to set the mechaism overhead values.

A slightly modified approach is for the forwarder to use the maximum overhead of all the supported mechanism types for **every** connection--not just the mechanism types used in that connection.  That would be a usable solution for the scenarios where the NSEs are relying on the forwarder for all connections.  I'm liking that approach since it wouldn't require NSEs adding custom overhead values.  

IMO, we might also want a forwarder config option to override the calculated MTUs for all connections since the NSM admin is likely to have a more complete view and need a way to override any cases that the calculated approach doesn't solve.

**Comment by rastislavs** [comment]
> The drawback is that it definitely requires our current NSEs to set the mechaism overhead values.

Only if the NSE provides a network function that requires a specific MTU overhead (e.g. for VXLAN/IPSec to somewhere else). Yes, in WCM case (vL3 case), since our NSE is doing tunnels to the other NSEs in other clusters, we always have to set its overhead value, which will be dependent on the actual tunneling technology that we use to interconnect NSEs in different clusters.

> Use the maximum overhead of all the supported mechanism types for every connection

I was thinking about this approach as well. I agree that it may be more convenient for our case, where we know that some remote mechanism is involved even when NSC and NSE are co-located on the same node. I just picked what I thought is a more generic NSM solution.

> we might also want a forwarder config option to override the calculated MTUs

Sure, I can add that.

**Comment by rastislavs** [comment]
Modified the code to use the max MTU overhead from:
 - maximum overhead of all the supported mechanism types
 - MTU overhead optionally set by NSE in the connection context (e.g. request.Connection.Context.SetMTUOverhead(50))

Also added the forwarder config option `ConnectionMTUOverride` (also configurable via `NSM_CONNECTION_MTU_OVERRIDE` env. var) which overrides the automatic MTU discovery.

**Comment by rastislavs** [comment]
One thing that is probably not correctly handled here is the mechanism update in runtime. Not sure how / when / why mechnisms can be updated in runtime?

https://github.com/cisco-app-networking/networkservicemesh/blob/eb1c73ae5557230b80cbe622c3fadc1f9f2f289f/forwarder/vppagent/pkg/vppagent/vppagent.go#L93-L113

**Comment by rastislavs** [comment]
Mechanism updates are now supported as well. Current result (no with no NSE changes:):
```
$ kubectl --context kind-kind-2 exec -it helloworld-example-6498d6c745-j67vf -- ip addr show dev nsm0
Defaulting container name to helloworld.
Use 'kubectl describe pod/helloworld-example-6498d6c745-j67vf -n default' to see all of the containers in this pod.
21: nsm0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc mq state UNKNOWN group default qlen 1000
    link/ether 02:fe:6a:04:f7:2e brd ff:ff:ff:ff:ff:ff
    inet 172.31.252.5/30 brd 172.31.252.7 scope global nsm0
       valid_lft forever preferred_lft forever
    inet6 fe80::fe:6aff:fe04:f72e/64 scope link 
       valid_lft forever preferred_lft forever
```

**Comment by tiswanso** [comment]
nice work, Rasto!  taking a final look

**Review by tiswanso — APPROVED** [review]
Looks good.  Let's get it in for additional testing.  We should follow up with a helm chart setting for the forwarder override MTU.

**Pull request merged**
